# Generated by Django 3.1.3 on 2022-02-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20220214_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='choice', max_length=200),
        ),
    ]
