# Generated by Django 3.1.3 on 2022-02-18 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_remove_submission_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='choices',
            field=models.ManyToManyField(to='onlinecourse.Choice'),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.ManyToManyField(to='onlinecourse.Choice')),
                ('submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.submission')),
            ],
        ),
    ]
