# Generated by Django 3.1.3 on 2022-02-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0011_auto_20220218_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='choice_id',
        ),
    ]
