# Generated by Django 3.1.3 on 2022-02-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0015_auto_20220220_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='choice_id',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='submission_id',
            new_name='submission',
        ),
    ]
